CREATE TABLE T_CLYVO_PESSOA (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(60),
    cpf VARCHAR2(14),
    data_nascimento DATE,
    email_pessoal VARCHAR2(100)
);

CREATE TABLE T_CLYVO_USUARIO (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_pessoa NUMBER(19,0),
    username VARCHAR2(50),
    senha VARCHAR2(255),
    permissao VARCHAR2(20),
    data_criacao DATE,
    CONSTRAINT fk_usuario_pessoa FOREIGN KEY (fk_pessoa) REFERENCES T_CLYVO_PESSOA(id)
);

CREATE TABLE T_CLYVO_RESPONSAVEL (
    id_responsavel NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_responsavel VARCHAR2(50) NOT NULL,
    cpf VARCHAR2(14),
    dt_nascimento DATE,
    email VARCHAR2(50) NOT NULL,
    num_celular VARCHAR2(20) NOT NULL
);

CREATE TABLE T_CLYVO_VETERINARIO (
    id_veterinario NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_veterinario VARCHAR2(50) NOT NULL,
    cpf VARCHAR2(14),
    dt_nascimento DATE,
    email VARCHAR2(50),
    num_celular VARCHAR2(20) NOT NULL,
    especialidade VARCHAR2(50) NOT NULL
);

CREATE TABLE T_CLYVO_ANIMAL (
    id_animal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_animal VARCHAR2(50),
    idade NUMBER(10,0),
    especie VARCHAR2(50),
    raca VARCHAR2(50),
    sexo VARCHAR2(1),
    dt_nascimento DATE,
    peso NUMBER,
    fk_id_responsavel NUMBER(19,0),
    CONSTRAINT fk_animal_responsavel FOREIGN KEY (fk_id_responsavel) REFERENCES T_CLYVO_RESPONSAVEL(id_responsavel)
);

CREATE TABLE T_CLYVO_DOENCA (
    id_doenca NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_doenca VARCHAR2(50),
    tipo VARCHAR2(50),
    contagiosidade VARCHAR2(1),
    descricao CLOB
);

CREATE TABLE T_CLYVO_VACINA (
    id_vacina NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_vacina VARCHAR2(50),
    tipo VARCHAR2(50),
    descricao CLOB
);

CREATE TABLE T_CLYVO_DOENCA_ANIMAL (
    id_doenca_animal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_diagnostico DATE,
    gravidade VARCHAR2(50),
    status VARCHAR2(50),
    observacoes CLOB,
    fk_id_animal NUMBER(19,0),
    fk_id_doenca NUMBER(19,0),
    CONSTRAINT fk_doencaanimal_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal),
    CONSTRAINT fk_doencaanimal_doenca FOREIGN KEY (fk_id_doenca) REFERENCES T_CLYVO_DOENCA(id_doenca)
);

CREATE TABLE T_CLYVO_VACINA_ANIMAL (
    id_vacina_animal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_doses NUMBER(10,0),
    frequencia_aplicacao NUMBER(10,0),
    dt_receita DATE,
    fk_id_vacina NUMBER(19,0),
    fk_id_animal NUMBER(19,0),
    CONSTRAINT fk_vacinaanimal_vacina FOREIGN KEY (fk_id_vacina) REFERENCES T_CLYVO_VACINA(id_vacina),
    CONSTRAINT fk_vacinaanimal_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

CREATE TABLE T_CLYVO_CONSULTA (
    id_consulta NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_agendamento DATE,
    dt_consulta DATE NOT NULL,
    fk_id_animal NUMBER(19,0),
    fk_id_veterinario NUMBER(19,0),
    CONSTRAINT fk_consulta_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal),
    CONSTRAINT fk_consulta_veterinario FOREIGN KEY (fk_id_veterinario) REFERENCES T_CLYVO_VETERINARIO(id_veterinario)
);

CREATE TABLE T_CLYVO_HISTORICO (
    id_historico NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_historico CLOB,
    dt_criacao_historico DATE,
    num_consultas_clyvo NUMBER,
    fk_id_consulta NUMBER(19,0),
    fk_id_animal NUMBER(19,0),
    CONSTRAINT fk_historico_consulta FOREIGN KEY (fk_id_consulta) REFERENCES T_CLYVO_CONSULTA(id_consulta),
    CONSTRAINT fk_historico_animal FOREIGN KEY (fk_id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);